services:
  - type: web
    name: contacts-manager-backend
    runtime: java
    rootDir: ContactApi backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/ContactApi-0.0.1-SNAPSHOT.jar
    plan: free